name: vtr_util
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  beautiful_soup_dart: ^0.3.0
  flutter:
    sdk: flutter
  http: ^1.0.0
  intl: ^0.18.1
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  syncfusion_flutter_pdf: ^21.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.1

flutter:
  uses-material-design: true
